engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - lib/**
  - bin/miga
