language: ruby
rvm:
  - jruby-9.0.5.0
  - jruby-1.7.24
jdk:
  - openjdk7
  - oraclejdk8
env: JRUBY_OPTS="-d"
before_script:
  - "export DISPLAY=:99.0"
  - "export SWT_GTK3=0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script: "bundle exec rake test:all"
after_script:
  - find -name '*.log' -exec cat {} \;
cache: bundler
addons:
  code_climate:
    repo_token: a7dc9fd6dc69b7ba0ad974b67a49df6c7df15fb6e08f712b4a9f148c67c1180c
